### ISSUE TITLE
tdf not working. 🔐🥺

### ISSUE THREAD

**Issue by sf338** [UOAF/Coastal-Front-Theater#73]
I have been trying various (every possible) methods and combinations for the past few days to connect the new theater to Falcon BMS. I even reinstalled the entire BMS, but despite all my efforts, I am unable to create the connection to the game. Would it be possible to upload also the executable (.exe) version directly to GitHub, in addition to the .zip file?

Please let me know if this is feasible, as this theater is very likely to become one of my most favorite.

Thank you for your help!

**Comment by sf338** [comment]
4.37\Data\TerrData\TheaterDefinition\Theater LST file

In that TheaterDefinition where are TDF and TGA
files of Korea is also not possible to connect it. I wrote right connection to it (tdf. of that theater) and also others, just to be sure, and tried to save it and it did save, but never with an Add-On before it..

**Comment by 3a7man** [comment]
If you unzip the file and tun the Alternative Launcher, you don't have to manually modify the LST file. Just unzip the file into the correct location.

**Comment by sf338** [comment]
@3a7man Also, sorry for the late reply. I tried it again, (with 7zip) but unfortunately, it still doesn’t work. I even tried downloading version 7, but nothing changed. But maybe it might be a bug with my PC (something with that launcher), though I’m not sure.
![IMG_7994](https://github.com/user-attachments/assets/fe3f15ef-80aa-47e7-82ab-773eda221908)

**Comment by 3a7man** [comment]
@sf338 
You're doing something wrong.
Check that you unzip the archive into:
 `Falcon BMS 4.37\Data` 
so that the path to the theater is:
`Falcon BMS 4.37\Data\Add-On Coastal Front`
In the above path you should see just the theater content such as `Art`,`Campaign` etc.
Then in the `theater.lst` you should add the theater path:
`Add-On Coastal Front\Terrdata\theaterdefinition\Coastal Front.tdf`

If this doesn't work, then either you need admin rights to modify the files or something is totally broken with the installation.

**Comment by sf338** [comment]
@3a7man I tried it again one last time and checked it (with the same result). Now, I believe the final answer is that there may be an issue with the structure of the TDF file (installation), or possibly a specific problem with my PC that even Windows updates haven’t resolved.

If the problem isn’t with my PC, then there might be a missing text/code somewhere in the TDF or TGA file. This could prevent the “Add-On” part from being added before “Add-On Coastal Front\Terrdata\theaterdefinition\Coastal Front.tdf” on some computers. As a result, it only adds it without the “Add-On,” even though the person manually overwrites it in the theater.lst file, including it properly.

Thank you for your time and effort spent on this so far, and in advance for any further assistance. 
👍

**Comment by sf338** [comment]
@3a7man I have already downloaded and tried all the available versions. I get the same error with all of them. There’s no possibility of connecting it to the BMS with the Add-On before it in the LST, with the launcher, or in any other way.

I connected it to the EMF some time ago, so it should work on my laptop, but it’s not working in this theater now.”

**Comment by 3a7man** [comment]
If you're on Falcon Lounge Discord, ping me to jump into a voice channel and sort it out. I will close this issue here.

**Comment by sf338** [comment]
@3a7man I cant now use discord, but thank you for your time and willingness 🎖️, have a nice day. 
I can survive for some time without It.
